# Generated by Django 3.0.5 on 2020-04-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20200417_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-04-20-00.37.05', max_length=100),
        ),
    ]
