# Generated by Django 2.2.11 on 2020-11-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0021_auto_20201119_2003'),
        ('words', '0020_auto_20200420_0037'),
    ]

    operations = [
    ]
