# Generated by Django 2.2.11 on 2020-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0024_auto_20201119_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-11-19-21.33.06', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_with_acute',
            field=models.CharField(max_length=100),
        ),
    ]
