# Generated by Django 2.2.11 on 2020-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0025_auto_20201119_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_with_acute',
            new_name='word_acute',
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-11-19-21.37.45', max_length=100),
        ),
    ]
